Finish code cleaning

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1228,16 +1228,16 @@ synthia-perform_installation() {
 
 	    }
 
-	    dna-set_option -o domain -v n -d y -p xmpp
+	    dna-set_option -o "domain" -p "xmpp" -d "y" -v "n"
 
 	    if [ $previous_value_outcome = "not-kept" ]
 	    then
 
 	        dna-echo -m "- * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! -"
 	        dna-echo -e "WARNING:"
-	        dna-echo -e "Changing domains will not preserve any user accounts or data. It will revert this server to a fresh install."
+	        dna-echo -e "Changing domains will not preserve any user accounts or data. It will revert this ejabberd instance to a fresh install."
 	        dna-echo -m "In the future, all user accounts and data for the previous domain might be recovered automatically if you ever re-run the install and select the old domain, but this hasn't been thoroughly tested yet."
-	        dna-echo -m "If you abort the domain change operation now, nothing will be deleted."
+	        dna-echo -m "If you answer no to the following question, nothing will be deleted."
 	        dna-echo -m "- * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! -"
 
 			ask_for_boolean_question="Are you absolutely sure you want to change the XMPP domain now?"
@@ -1317,7 +1317,7 @@ synthia-perform_installation() {
 
 		### Set node_number to 01 as this is the primary node
 
-		dna-set_option -o node_number -p cluster -s "01"
+		dna-set_option -o "node_number" -p "cluster" -s "01"
 
 		### Initialize nodes_db files
 
@@ -1333,8 +1333,9 @@ synthia-perform_installation() {
 
 		### As this is a secondary node, we need to join an existing ejabberd cluster and therefore start clean and remove any ejabberd data already present on this server.
 
-		dna-echo -e "Proceeding with this installation as a secondary node will wipe any and everything is already present on this [only this] server."
+		dna-echo -e "Proceeding with this installation as a secondary node will wipe anything and everything that might already present on this [and only this] server."
 		dna-echo -m "If this node is currently part of a cluster, data on other nodes will NOT be affected, and this node will re-obtain all cluster data from other nodes upon completion of the installation."
+		dna-echo -m "If however you've previously used this machine to host a standalone installation or not-yet-clusterized data, this will be permanently lost."
 		dna-echo -m "Please ensure there is no UNIQUE [as in non-clustered] and VALUABLE [as in you don't want to lose] data on this machine."
 
 		ask_for_boolean_question="Proceed with wiping any ejabberd-related data on this server during the course of this installation?"
@@ -1399,7 +1400,7 @@ synthia-perform_installation() {
 
 	    dna-echo -m "It's time to set up the LetsEncrypt wildcard TLS [SSL] certificate that will be valid for | *.${domain} |."
 
-		dna-provision_le_wildcard_cert -d "$domain"
+		dna-provision_le_wildcard_cert -d "${domain}"
 
 		#### Copy the LetsEncrypt post-renewal script to its location and actually run it now to be ready for the installation
 
@@ -1415,6 +1416,8 @@ synthia-perform_installation() {
 	        dna-echo -e "Something went wrong provisioning the wildcard TLS certificate for ${domain}."
 	        dna-exit
 	    fi
+
+		clear
 
 		########################################################################
 
@@ -1432,7 +1435,7 @@ synthia-perform_installation() {
 
 		### Generate token [or use the public IPv6 address of this machine if available] as visual fingerprint for user connection checking
 
-		if [ $ipv6_available = "y" ]
+		if [ "${ipv6_available}" = "y" ]
 		then
 			echo "${this_ipv6}" > "${temp_dir}/aenigma-cluster-token"
 		else
@@ -1443,25 +1446,25 @@ synthia-perform_installation() {
 		########################################################################
 
 		dna-echo -m "This is the public IPv4 for this machine:"
-		dna-echo -m " | ${g-}$this_ipv4${n-} | "
+		dna-echo -m " | ${y-}$this_ipv4${n-} | "
 		dna-echo -m "Enter it on the primary node when prompted to do so, then follow the instructions from there."
 
 		sleep 1
 
 		########################################################################
 
-		if [ -f /root/.ssh/authorized_keys ]
+		if [ -f "${ssh_auth_keys_file}" ]
 		then
 	        dna-echo -s "SSH Authorized Keys file found."
 		else
-			dna-echo -m "$SSH Authorized Keys file NOT found. Creating it now..."
-			mkdir -p /root/.ssh/
-	        touch /root/.ssh/authorized_keys
+			dna-echo -m "SSH Authorized Keys file NOT found. Creating it now."
+			mkdir -p "/root/.ssh/"
+	        touch "${ssh_auth_keys_file}"
 		fi
 
 		########################################################################
 
-		if grep -q "root@ae01." /root/.ssh/authorized_keys
+		if grep -q "root@ae01." "${ssh_auth_keys_file}"
 		then
 
 			dna-echo -s "An SSH public key generated by the primary node was already previously saved on this server."
@@ -1472,12 +1475,12 @@ synthia-perform_installation() {
 
 				if [ -f "${temp_dir}/aenigma-cluster-ssh-connection-successful" ]
 				then
-					condition_verified=y
+					condition_verified="y"
 				fi
 
 			}
 
-			dna-wait_for -m 32 -d "Now looking to see if the primary node is already able to connect to this node..."
+			dna-wait_for -m "32" -d "Now looking to see if the primary node is already able to connect to this node..."
 
 			if [ "${wait_output}" = "ok" ]
 			then
@@ -1507,7 +1510,7 @@ synthia-perform_installation() {
 
 					if [ -f "${temp_dir}/aenigma-cluster-ssh-connection-successful" ]
 					then
-						valid=y
+						valid="y"
 					else
 						dna-echo -e "The primary node still does NOT appear to have been able to successfully connect to this node."
 						dna-echo -m "Ensure its connection to this machine has actually succeeded and, if not, specify the public SSH key it will display shortly."
@@ -1520,10 +1523,10 @@ synthia-perform_installation() {
 
 					if [ "${key_is_valid}" = "y" ]
 					then
-						valid=y
+						valid="y"
 					else
 						dna-echo -e "The key you specified does NOT appear to be a valid SSH Public Key."
-						valid=n
+						valid="n"
 					fi
 
 				fi
@@ -1532,9 +1535,9 @@ synthia-perform_installation() {
 
 			if [ "${primary_node_ssh_connection-null}" = "attempted" ]
 			then
-				dna-set_value -d "Now specify the public SSH key [or write | ${y-}skip${n-} | if the connection was already successful]:" -v y
+				dna-set_value -d "Now specify the public SSH key [or write | ${y-}skip${n-} | if the connection was already successful]:" -v "y"
 			else
-				dna-set_value -d "Now specify the public SSH key displayed that will be displayed shortly on the primary node:" -v y
+				dna-set_value -d "Now specify the public SSH key displayed that will be displayed shortly on the primary node:" -v "y"
 			fi
 
 			cluster_ssh_pubkey="${value}"
@@ -1542,9 +1545,9 @@ synthia-perform_installation() {
 			if [ ! "${value}" = "skip" ]
 			then
 
-				if ! grep -q "${cluster_ssh_pubkey}" /root/.ssh/authorized_keys
+				if ! grep -q "${cluster_ssh_pubkey}" "${ssh_auth_keys_file}"
 				then
-					echo "$cluster_ssh_pubkey" >> /root/.ssh/authorized_keys
+					echo "$cluster_ssh_pubkey" >> "${ssh_auth_keys_file}"
 				fi
 
 			fi
@@ -1569,7 +1572,7 @@ synthia-perform_installation() {
 
 			if [ -f "${temp_dir}/aenigma-cluster-primary-node-setup-complete" ]
 			then
-				condition_verified=y
+				condition_verified="y"
 			fi
 
 		}
@@ -1614,9 +1617,16 @@ synthia-perform_installation() {
 
 	############################################################################
 
-	### Stop SSLH to avoid conflicts with any brand new nginx installation
+	### Stop SSLH to avoid any conflicts with a brand new nginx installation
 
-	/usr/sbin/service sslh stop &> /dev/null || true
+	if systemctl is-active --quiet sslh
+	then
+
+		dna-echo -m "Now stopping SSLH..."
+		/usr/sbin/service sslh stop
+		dna-echo -s "Finished stopping SSLH."
+
+	fi
 
 	### Install nginx and configure ejabberd admin panel reverse proxy site
 
@@ -1651,9 +1661,9 @@ synthia-perform_installation() {
 		ln -s "/etc/nginx/sites-available/${proj_name}" "/etc/nginx/sites-enabled/${proj_name}"
 	fi
 
-	service nginx reload || true
+	### Reload nginx
 
-	############################################################################
+	service nginx reload || true
 
 	### Restart nginx
 
@@ -1673,23 +1683,23 @@ synthia-perform_installation() {
 
 		### Determine if this is a fresh install
 
-		if [ ! -f /var/lib/ejabberd/LATEST.LOG ]
+		if [ ! -f "/var/lib/ejabberd/LATEST.LOG" ]
 		then
 
 			### This is a fresh install, we can proceed with customizing the ERLANG_NODE value in the /etc/default/ejabberd config file and wiping the data directory after installing ejabberd.
 
-			set_erlang_node_to_hostname=ok
-			wipe_var_lib_ejabberd=ok
+			set_erlang_node_to_hostname="ok"
+			wipe_var_lib_ejabberd="ok"
 
 		else
 
 			### This is a re-install.
 
-			wipe_var_lib_ejabberd=no
+			wipe_var_lib_ejabberd="no"
 
 			### Check to see if config file already exists.
 
-			if [ -f /etc/default/ejabberd ]
+			if [ -f "/etc/default/ejabberd" ]
 			then
 
 				### The config file is in place. Check to see if the ERLANG_NODE value is already correct.
@@ -1699,7 +1709,7 @@ synthia-perform_installation() {
 
 					### The configuration is already correct, the existing data in /var/lib/ejabberd will work fine.
 
-					set_erlang_node_to_hostname=no
+					set_erlang_node_to_hostname="no"
 
 				else
 
@@ -1716,7 +1726,7 @@ synthia-perform_installation() {
 						read -rp "${b-}Press enter to continue...${x-}"
 						echo
 
-						set_erlang_node_to_hostname=ok
+						set_erlang_node_to_hostname="ok"
 
 					else
 
@@ -1738,7 +1748,7 @@ synthia-perform_installation() {
 						read -rp "${b-}Press enter to continue...${x-}"
 						echo
 
-						set_erlang_node_to_hostname=no
+						set_erlang_node_to_hostname="no"
 
 					fi
 
@@ -1763,7 +1773,7 @@ synthia-perform_installation() {
 
 				fi
 
-				set_erlang_node_to_hostname=ok
+				set_erlang_node_to_hostname="ok"
 
 			fi
 
@@ -1773,8 +1783,8 @@ synthia-perform_installation() {
 
 		### This is a secondary node install, the user has already consented to a full wipe, we can therefore proceed with customizing the ERLANG_NODE value in the ejabberdctl.cfg config file and wiping the data directory after installing ejabberd.
 
-		set_erlang_node_to_hostname=ok
-		wipe_var_lib_ejabberd=ok
+		set_erlang_node_to_hostname="ok"
+		wipe_var_lib_ejabberd="ok"
 
 	fi
 
@@ -1860,7 +1870,7 @@ synthia-perform_installation() {
 	sed -i "s/xp.@/xp${node_number}.@/g" /etc/ejabberd/ejabberd.yml
 	sed -i "s/xu.@/xu${node_number}.@/g" /etc/ejabberd/ejabberd.yml
 
-	sed -i "/INET_DIST_INTERFACE=/c\INET_DIST_INTERFACE=${this_ipv4}" /etc/default/ejabberd
+	sed -i "/INET_DIST_INTERFACE=/c\INET_DIST_INTERFACE=${this_ipv4}" "/etc/default/ejabberd"
 
 	if [ "${set_erlang_node_to_hostname}" = "ok" ]
 	then
@@ -1889,10 +1899,6 @@ synthia-perform_installation() {
 	if [ ! "${cluster_mode-null}" = "secondary" ]
 	then
 
-		### Proceed with primary node installation
-
-		########################################################################
-
 		### Add backup script to crontab
 
 		dna-add_cron_job -n ${proj_name}-backup -t "8 4 * * *" -c "bash /root/openspace42/${proj_name}/tools/${proj_name}-backup"
@@ -1906,11 +1912,11 @@ synthia-perform_installation() {
 
 		if [ -f "${conf_xmpp_dir}/ejabberd_admin_password_set" ]
 		then
-		    read -rp "${b-}Leave ejabberd admin user password the same as previously set? (Y/n): ${x-}" -n 1
-		    echo
-		    if [[ ! $REPLY =~ ^[Nn]$ ]]
-		    then
-		        dna-echo -m "Skipping ejabberd admin user password reset."
+			ask_for_boolean_question="Leave ejabberd admin user password the same as previously set?"
+            dna-ask_for_boolean_def_yes
+            if [ "$ask_for_boolean_output" = "y" ]
+            then
+		        dna-echo -m "Ok, skipping ejabberd admin user password reset."
 		        ejab_admin_pwreset="n"
 		    else
 		        echo
@@ -1947,77 +1953,38 @@ synthia-perform_installation() {
 	############################################################################
 	############################################################################
 
-	### Run a generic APT operation to catch its output and alert the user if something has gone wrong
+	### Run some generic operations to catch services status output and alert the user if something has gone wrong.
 
-	echo "${b-}Now performing a final run of APT to ensure all package installations have completed successfully...${x-}"
-	echo
-	set +e
-	if apt-get -y upgrade
-	then
-	    echo
-	    echo "${g-}${b-}All APT package installations completed successfully...${x-}"
-	    echo
-	else
-	    echo
-	    echo "${r-}${b-}An error has occured during APT operations.${x-}"
-	    echo
-	    echo "${b-}This was the last step in this installation, so it's possible your end result is at least partially working.${x-}"
-	    echo
-	    echo "${b-}Please review the above log and try running the installation again. If necessary open an issue on github. Thank you.${x-}"
-	    echo
-	    read -rp "${b-}[press enter to continue reading...]${x-}"
-	fi
-	set -e
+	declare -A service_checker_array=(
+			[APT]="apt-get -y upgrade"
+			[NGINX]="/usr/sbin/service nginx restart"
+			[SSLH]="/usr/sbin/service sslh restart"
+		)
 
-	### Run an nginx restart to catch its output and alert the user if something has gone wrong
+	for service in "${!service_checker_array[@]}"
+	do
 
-	echo "${b-}Now performing a final restart of NGINX to ensure all related installations have completed successfully...${x-}"
-	echo
-	set +e
-	if service nginx restart
-	then
-	    echo "${g-}${b-}All nginx installations completed successfully...${x-}"
-	    echo
-	else
-	    echo "${r-}${b-}An error has occured during nginx operations.${x-}"
-	    echo
-	    echo "${b-}This was the last step in this installation, so it's possible your end result is at least partially working.${x-}"
-	    echo
-	    echo "${b-}Please review the above log and try running the installation again. If necessary open an issue on github. Thank you.${x-}"
-	    echo
-	    read -rp "${b-}[press enter to continue reading...]${x-}"
-	fi
-	set -e
+		set +e
 
-	### Run an sslh restart to catch its output and alert the user if something has gone wrong
+		if "${service_checker_array[$service]}"
+		then
+			dna-echo -s "All | ${n-}${service}${g-} | operations completed successfully."
+		else
+			dna-echo -e "An error has occured during | ${n-}${service}${g-} | operations."
+			dna-echo -m "This was one of the last steps in this installation, so it's possible that your end result is at least partially working."
+			dna-echo -m "Review the output above and try running the installation again."
+			read -rp "${b-}[press enter to continue reading...]${x-}"
+		fi
 
-	echo "${b-}Now performing a final restart of SSLH to ensure all related installations have completed successfully...${x-}"
-	echo
-	set +e
-	if service sslh restart
-	then
-	    echo "${g-}${b-}All sslh installations completed successfully...${x-}"
-	    echo
-	else
-	    echo "${r-}${b-}An error has occured during sslh operations.${x-}"
-	    echo
-	    echo "${b-}This was the last step in this installation, so it's possible your end result is at least partially working.${x-}"
-	    echo
-	    echo "${b-}Please review the above log and try running the installation again. If necessary open an issue on github. Thank you.${x-}"
-	    echo
-	    read -rp "${b-}[press enter to continue reading...]${x-}"
-	fi
-	set -e
+		set -e
+
+	done
 
 	############################################################################
 	############################################################################
 
 	if [ ! "${cluster_mode-null}" = "secondary" ]
 	then
-
-		### Proceed with primary node installation
-
-		########################################################################
 
 		### Pring login information and credentials
 
@@ -2051,6 +2018,7 @@ synthia-perform_installation() {
 				read -rp "${b-}[press enter to continue reading...]${x-}"
 				echo
 			fi
+
 		fi
 
 	else
@@ -2062,6 +2030,7 @@ synthia-perform_installation() {
 			dna-echo -s "The ejabberd cluster was successfully joined!"
 		else
 			dna-echo -e "The ejabberd cluster join operation failed."
+			dna-echo -m "Inspect the | ${y-}/var/log/ejabberd/error.log${n-} | logfile for more information."
 			dna-exit
 		fi
 
