restore missing chunk of code thanks to solushq

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1952,6 +1952,393 @@ aenigma-create_nodes_db_initial() {
 
 aenigma-compare_nodes_db_initial() {
 
+	if diff "${nodes_db_numbered_path}" "${nodes_db_initial_path}" > /dev/null
+	then
+	    export nodes_db_initial_diff="same"
+	else
+	    export nodes_db_initial_diff="diff"
+	fi
+
+}
+
+aenigma-initialize_nodes_db_files() {
+
+	mkdir -p "${conf_cluster_nodes_dir}"
+
+	dna-get_public_ipv4 -s
+
+	dna-check_ipv6_connectivity -s
+
+	### IPv4
+
+	touch "${nodes_db_ipv4_path}"
+
+	if [ -s "${nodes_db_ipv4_path}" ]
+	then
+		### File is not empty, alter first line.
+		sed -i "1s/.*/${public_ipv4}/" "${nodes_db_ipv4_path}"
+	else
+		### File is empty, write to it.
+		echo "${public_ipv4}" > "${nodes_db_ipv4_path}"
+	fi
+
+	### IPv6
+
+	touch "${nodes_db_ipv6_path}"
+
+	if [ -s "${nodes_db_ipv6_path}" ]
+	then
+
+		### File is not empty, alter first line.
+
+		if [ "${ipv6_available}" = "y" ]
+		then
+			sed -i "1s/.*/${this_ipv6}/" "${nodes_db_ipv6_path}"
+		else
+			sed -i "1s/.*/null/" "${nodes_db_ipv6_path}"
+		fi
+
+	else
+
+		### File is empty, write to it.
+
+		if [ "${ipv6_available}" = "y" ]
+		then
+			echo "${this_ipv6}" > "${nodes_db_ipv6_path}"
+		else
+			echo "null" > "${nodes_db_ipv6_path}"
+		fi
+
+	fi
+
+	aenigma-create_nodes_db_numbered
+
+}
+
+aenigma-get_ejabberd_cluster_size() {
+
+	ejabberd_cluster_size="$(wc -l < ${nodes_db_ipv4_path})"
+
+}
+
+aenigma-wipe_old_ufw_cluster_rules() {
+
+	### Remove any and all UFW rules related to old cluster nodes
+
+	############################################################################
+
+	### Only do this check if ufw has actually been initialized
+
+	if systemctl is-active --quiet ufw
+	then
+
+		### Get "ufw allow from x.x.x.x" rules previously set by us
+
+		ufw show added | grep "ufw allow from" | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' > "${tmp_dir}/ufw_previous_cluster_rules" || true
+
+		### Check every item from previous command output to see if those IPv4s
+		### are still part of the cluster and if not remove those rules
+
+		while read line
+		do
+
+			if [ ! "${line}" = "" ]
+			then
+
+				if ! grep -qr "${line}" "${conf_cluster_nodes_dir}"
+				then
+
+					ufw --force delete "$(ufw status | grep -E ' (ALLOW|LIMIT) ' | grep -n ${line} | cut -f1 -d":")"
+
+				fi
+
+			fi
+
+		done < "${tmp_dir}/ufw_previous_cluster_rules"
+
+		unset line
+
+		rm "${tmp_dir}/ufw_previous_cluster_rules"
+
+	fi
+
+	############################################################################
+
+}
+
+aenigma-update_routing_info() {
+
+	### Wipe any old cluster-related UFW rule
+
+	aenigma-wipe_old_ufw_cluster_rules
+
+	### Set UFW rules on this node according to the updated nodes_db
+
+	array_iter=1
+	IFS=$'\n'
+	set -f
+	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")
+	do
+		/usr/sbin/ufw insert "${array_iter}" allow from "${node_ipv4}"
+		array_iter=$((array_iter + 1))
+	done
+	unset node_ipv4 array_iter
+	IFS=$' \t\n'
+	set +f
+	echo
+
+	### Import nodes_db to /etc/hosts to provide ejabberd with a locally resolved list of nodes to cluster with
+
+	if ! grep -q "### aenigma nodes list start" /etc/hosts
+	then
+		echo >> /etc/hosts
+		echo "### aenigma nodes list start" >> /etc/hosts
+	fi
+
+	if ! grep -Pzoq '### aenigma nodes list start(?:.*\n)*?\K### aenigma nodes list end' /etc/hosts
+	then
+		echo "### aenigma nodes list end" >> /etc/hosts
+	fi
+
+	sed -i '/### aenigma nodes list start/,/### aenigma nodes list end/{//!d}' /etc/hosts
+	sed -i "/### aenigma nodes list start/ r ${nodes_db_numbered_path}" /etc/hosts
+
+}
+
+aenigma-refresh_nodes_db_online() {
+
+	############################################################################
+
+	### This function will always get invoked at the beginning push_routing_info() in the later event that an existing node cannot be reached at the time of running a new clusterization.
+	### It will create a copy of nodes_db_ipv4 and nodes that appear to be offline will be removed from it, for use by subsequent functions, until the end of the clusterize script.
+
+	############################################################################
+
+	### Touch temp dir
+
+	dna-touch_tmp_project_dir
+
+	############################################################################
+
+	if [ -f "${nodes_db_online_path}" ]
+	then
+		rm "${nodes_db_online_path}"
+		touch "${nodes_db_online_path}"
+	fi
+
+	############################################################################
+
+	cp "${nodes_db_ipv4_path}" "${nodes_db_online_path}"
+
+	############################################################################
+
+}
+
+aenigma-get_nodes_online() {
+
+	############################################################################
+
+	### Generate a list of online nodes by opening SSH sessions to other nodes.
+	### If any nodes are offline, remove them from nodes_db_online.
+
+	aenigma-refresh_nodes_db_online
+
+	array_iter=1
+	IFS=$'\n'
+	set -f
+
+	touch "${tmp_dir}/online_test_token"
+
+	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")							### Do NOT escape this variable
+	do
+		current_node_number="$(echo ${array_iter} | xargs printf %02d)"
+		### Ensure we don't try connecting to ourselves [therefore ignore the first line of nodes_db_ipv4].
+		if [ ! "${node_ipv4}" = "${public_ipv4}" ]
+		then
+			if ! /usr/bin/scp -P42022 -o "ConnectTimeout=8" -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i "/root/.ssh/aenigma_cluster" -r "${tmp_dir}/online_test_token" "root@${node_ipv4}:${tmp_dir}/online_test_token"
+			then
+				echo
+				dna-echo -e "Existing node number | ${n-}${current_node_number}${r-} | is not responding at IPv4 address | ${n-}${node_ipv4}${r-} |."
+				dna-echo -m "It is NOT reccommended to continue the installation as the node in question will not be informed of the new node we're setting up right now."
+				dna-echo -m "However, you can continue running the installation now and re-run the installation script at at a later time."
+	            dna-ask_for_boolean -d "y" -q "Continue anyway?"
+	            if [ "${boolean_output}" = "y" ]
+	            then
+					dna-echo -n -m "Ok, continuing..."
+					### Remove node from nodes_db_online
+					sed -i "/^${node_ipv4}$/d" "${nodes_db_online_path}"
+				else
+					dna-echo -m "Ok, aborting..."
+					dna-exit
+				fi
+			fi
+		fi
+		array_iter=$((array_iter + 1))
+	done
+	unset node_ipv4
+	IFS=$' \t\n'
+	set +f
+
+}
+
+aenigma-check_ip_info_current() {
+
+	if [ ! -f "${nodes_db_ipv4_path}" ] || [ ! -f "${nodes_db_ipv6_path}" ]
+    then
+		dna-echo -m "Not all nodes_db files found or none at all. Skipping IP change checks."
+        return 0
+    fi
+
+	### Fetch IP addresses for this machine
+
+	dna-get_public_ipv4
+
+	dna-check_ipv6_connectivity
+
+	### Check to see if this machine's IPs have changed since last install / clusterization
+
+	this_registered_ipv4="$(cat ${nodes_db_ipv4_path} | head -1 | xargs)"
+
+	this_registered_ipv6="$(cat ${nodes_db_ipv6_path} | head -1 | xargs)"
+
+	if [ ! "${public_ipv4}" = "${this_registered_ipv4}" ]
+	then
+		dna-echo -e "The public IPv4 address for this machine appears to have changed since the last install or the last run of the clusterize script."
+		dna-echo -m "It now appears to be: | ${y-}${public_ipv4}${n-} |."
+		dna-echo -m "This node, however, appears to be registered with the following: | ${y-}${this_registered_ipv4}${n-} |."
+		dna-echo -m "Please re-run the installation to update the records for this machine on the nodes database."
+		dna-exit
+	fi
+
+	if [ ! "${this_ipv6}" = "${this_registered_ipv6}" ]
+	then
+		dna-echo -e "The public IPv6 address for this machine appears to have changed since the last install or the last run of the clusterize script."
+		dna-echo -m "It now appears to be: | ${y-}${this_ipv6}${n-} |."
+		dna-echo -m "This node, however, appears to be registered with the following: | ${y-}${this_registered_ipv6}${n-} |."
+		dna-echo -m "Please re-run the installation to update the records for this machine on the nodes database."
+		dna-exit
+	fi
+
+}
+
+aenigma-push_routing_info() {
+
+	############################################################################
+
+	### Push nodes_db files to all secondary nodes for /etc/hosts and ufw rules configuration.
+	### At the same time, check to see if any existing secondary nodes are offline, and, if so, remove them from nodes_db_online.
+
+	aenigma-refresh_nodes_db_online
+
+	array_iter=1
+	IFS=$'\n'
+	set -f
+
+	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")							### Do NOT escape this variable
+	do
+		current_node_number="$(echo ${array_iter} | xargs printf %02d)"
+		### Ensure we don't try connecting to ourselves [therefore ignore the first line of nodes_db_ipv4].
+		if [ ! "${node_ipv4}" = "${public_ipv4}" ]
+		then
+			if ! /usr/bin/scp -P42022 -o "ConnectTimeout=8" -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i /root/.ssh/aenigma_cluster -r "${conf_cluster_nodes_dir}" "root@${node_ipv4}:${conf_cluster_dir}"
+			then
+				echo
+				dna-echo -e "Existing node number | ${n-}${current_node_number}${r-} | is not responding at IPv4 address | ${n-}${node_ipv4}${r-} |."
+				dna-echo -m "It is NOT reccommended to continue the installation as the node in question will not be informed of the new node we're setting up right now."
+				dna-echo -m "However, you can continue running the installation now and run the | ${o-}push_routing_info${n-} | script at at a later time by executing:"
+				dna-echo -m " | ${y-}bash ${tools_dir}/${proj_name}-push_routing_info${n-} | "
+	            dna-ask_for_boolean -d "y" -q "Continue anyway?"
+	            if [ "${boolean_output}" = "y" ]
+	            then
+					dna-echo -n -m "Ok, continuing..."
+					### Remove node from nodes_db_online
+					sed -i "/^${node_ipv4}$/d" "${nodes_db_online_path}"
+				else
+					dna-echo -m "Ok, aborting..."
+					dna-exit
+				fi
+			fi
+		fi
+		array_iter=$((array_iter + 1))
+	done
+	unset node_ipv4
+	IFS=$' \t\n'
+	set +f
+
+	############################################################################
+
+	aenigma-exec() {
+
+		### Define the commands that will be passed to the aenigma-exec script on the remote machine to be run, one per line between the quotes.
+
+        bash openspace42/aenigma/tools/aenigma-exec -c "
+aenigma-update_routing_info
+"
+
+	}
+
+	############################################################################
+
+	for online_node_ipv4 in $(cat < "${nodes_db_online_path}")
+	do
+		### Ensure we don't try connecting to ourselves [therefore ignore the first line of nodes_db_ipv4].
+		if [ ! "${online_node_ipv4}" = "${public_ipv4}" ]
+		then
+			### SSH into the secondary node, declare the aenigma-exec function, and run it inside of the subshell.
+	        ssh -tt -p42022 -o "BatchMode=yes" -o "ConnectTimeout=8" -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i "/root/.ssh/aenigma_cluster" "root@${online_node_ipv4}" "$(declare -f aenigma-exec); export -f aenigma-exec; exec bash -li" <<END
+set -eu
+. /root/openspace42/aenigma/functions
+synthia-source_dna
+synthia-define_vars
+dna-read_conf_settings
+aenigma-exec
+exit
+END
+		fi
+		echo
+	done
+	unset online_node_ipv4
+
+	############################################################################
+
+}
+
+aenigma-push_certs() {
+
+	############################################################################
+
+	### Push LetsEncrypt TLS certificate files to all secondary nodes.
+	### At the same time, check to see if any existing secondary nodes are offline, and, if so, remove them from nodes_db_online.
+
+	aenigma-refresh_nodes_db_online
+
+	array_iter=1
+	IFS=$'\n'
+	set -f
+
+	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")							### Do NOT escape this variable
+	do
+		current_node_number="$(echo ${array_iter} | xargs printf %02d)"
+		### Ensure we don't try connecting to ourselves [therefore ignore the first line of nodes_db_ipv4].
+		if [ ! "${node_ipv4}" = "${public_ipv4}" ]
+		then
+			if ! /usr/bin/scp -P42022 -o "ConnectTimeout=8" -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i /root/.ssh/aenigma_cluster -r "${tls_project_dir}" "root@${node_ipv4}:${tls_dir}"
+			then
+				echo
+				dna-echo -e "Node number | ${n-}${current_node_number}${r-} | is not responding at IPv4 address | ${n-}${node_ipv4}${r-} |."
+				dna-echo -m "Ensure such node is actually online and when it is execute this script again by running:"
+				dna-echo -m " | ${y-}${tools_dir}/${proj_name}-create-push-certs${n-} | "
+				if [ "${interactive}" = "y" ]
+				then
+		            dna-ask_for_boolean -d "y" -q "Continue anyway with all other nodes now?"
+		            if [ "${boolean_output}" = "y" ]
+		            then
+						dna-echo -n -m "Ok, continuing..."
+						### Remove node from nodes_db_online
+						sed -i "/^${node_ipv4}$/d" "${nodes_db_online_path}"
+					else
+						dna-echo -m "Ok, aborting..."
+						dna-exit
 					fi
 				else
 					dna-echo -e "Skipping node | ${n-}${current_node_number}${r-} | and continuing with all others now."
