Update to clusterization functions

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -381,7 +381,10 @@ perform_installation() {
 
 	os-install_duplicity
 
-	mkdir -p "$tls_dir"
+	mkdir -p "${tls_dir}"
+	chown -R ejabberd:ejabberd "${tls_dir}"
+	chmod -R 700 "${tls_dir}"
+
 	mkdir -p "$temp_dir"
 
 	################################################################################
@@ -1096,7 +1099,8 @@ perform_installation() {
 
 		echo "${b}Now creating uploads directory...${x}"
 		echo
-		mkdir -p /etc/ejabberd/uploads/
+		mkdir -p /var/lib/ejabberd/uploads
+		chown ejabberd:ejabberd /var/lib/ejabberd/uploads
 		echo "${b}Finished creating uploads directory.${x}"
 		echo
 
@@ -1104,7 +1108,9 @@ perform_installation() {
 
 		echo "${b}Now creating HTTP fileserver directory...${x}"
 		echo
-		mkdir -p /var/www/ejabberd/
+		mkdir -p "/var/www/ejabberd/"
+		chown -R ejabberd:ejabberd "/var/www/ejabberd/"
+		chmod -R 755 "/var/www/ejabberd/"
 		echo "${b}Finished creating HTTP fileserver directory.${x}"
 		echo
 
@@ -1114,6 +1120,7 @@ perform_installation() {
 		echo
 		mkdir -p /var/log/ejabberd/
 		touch /var/log/ejabberd/www_access.log
+		chown ejabberd:adm /var/log/ejabberd/www_access.log
 		echo "${b}Finished creating logfile.${x}"
 		echo
 
@@ -1170,23 +1177,6 @@ perform_installation() {
 		echo "${b}Finished installing ejabberd.${x}"
 		echo
 
-		### Secure permissions
-
-		echo "${b}Now securing permissions...${x}"
-		echo
-
-		chown -R ejabberd:ejabberd $tls_dir
-		chmod -R 700 $tls_dir
-
-		chown -R ejabberd:ejabberd /etc/ejabberd/uploads/
-		chmod -R 755 /etc/ejabberd/uploads/
-
-		chown -R ejabberd:ejabberd /var/www/ejabberd/
-		chmod -R 755 /var/www/ejabberd/
-
-		echo "${b}Finished securing permissions.${x}"
-		echo
-
 		### Restart ejabberd and ensure it correctly comes up
 
 		echo "${b}Now stopping ejabberd...${x}"
@@ -1210,12 +1200,6 @@ perform_installation() {
 		rm -rf /var/lib/ejabberd/*
 
 		# Substitute .erlang.cookie with primary node's in the future for clusterization
-
-		mkdir /var/lib/ejabberd/uploads
-		chown ejabberd:ejabberd /var/lib/ejabberd/uploads
-
-		touch /var/log/ejabberd/www_access.log
-		chown ejabberd:adm /var/log/ejabberd/www_access.log
 
 		echo "${b}Now starting ejabberd...${x}"
 		/usr/sbin/service ejabberd start
@@ -1375,7 +1359,94 @@ perform_installation() {
 
 		### Proceed with secondary node install
 
+		########################################################################
+
+		echo "${b}This is the public IPv4 for this machine:${x}"
 		echo
+		echo "${b} | ${g}$this_ipv4${x}${b} | ${x}"
+		echo
+		echo "${b}Enter it on the primary node when prompted to do so.${x}"
+		echo
+		read -rp "${b}[press enter when done to continue...]${x}"
+		clear
+
+		########################################################################
+
+		if [ -f /root/.ssh/authorized_keys ]; then
+	        echo "${g}${b}SSH Authorized Keys file found.${x}"
+	        echo
+		else
+			echo "${b}SSH Authorized Keys file NOT found. Creating it now...${x}"
+			echo
+			mkdir -p /root/.ssh/
+	        touch /root/.ssh/authorized_keys
+		fi
+
+		chown root:root /root/.ssh/authorized_keys
+		chmod 600 /root/.ssh/authorized_keys
+
+		defined=n
+		until [ $defined = "y" ]
+		do
+			clusterize_ssh_pubkey=""
+			until [ ! "$clusterize_ssh_pubkey" = "" ]
+			do
+				read -rp "${b}Now specify the public SSH key displayed on the primary node: ${x}" clusterize_ssh_pubkey
+				echo
+			done
+			valid=n
+			until [ $valid = "y" ]
+			do
+				read -n 1 -p "${b}Is it correct? (Y/n/e[xit]) ${x}" answer;
+				case $answer in
+				"")
+					echo
+					valid=y
+					defined=y
+					;;
+				y)
+					echo -e "\n"
+					valid=y
+					defined=y
+					;;
+				n)
+					echo -e "\n"
+					echo "${b}Ok, then please try again...${x}"
+					echo
+					valid=y
+					defined=n
+					;;
+				e)
+					echo -e "\n"
+					echo "${b}Exiting...${x}"
+					echo
+					exit
+					;;
+				*)
+					echo -e "\n"
+					echo "${r}${b}Invalid option. Retry...${x}"
+					echo
+					valid=n
+					defined=n
+					;;
+				esac
+			done
+		done
+
+		if ! grep -q "${clusterize_ssh_pubkey}" /root/.ssh/authorized_keys
+		then
+			echo "$clusterize_ssh_pubkey" > /root/.ssh/authorized_keys
+		fi
+
+		### Generate token for user connection checking
+
+		aenigma_clusterize_token="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 24 | head -n 1)"
+		echo "${aenigma_clusterize_token}" > /tmp/aenigma_clusterize_token
+
+		echo "${b}Now continue setup on the primary node to ensure the SSH connection is working correctly.${x}"
+		echo
+		read -rp "${b}[press enter to continue...]${x}"
+		clear
 
 	fi
 
