install ejabberd from process-one package downloads rather than jabber.at apt repo

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -55,6 +55,13 @@ synthia-define_vars() {
 	export nodes_db_online_path="${tmp_project_dir}/nodes_db_online"
 	export nodes_db_initial_path="${tmp_project_dir}/nodes_db_initial"
 
+	### Hardcode package versions for installation
+
+	export hardcoded_package_version_ejabberd="19.05"
+	export hardcoded_package_version_ejabberd_extended="19.05-0"
+	export hardcoded_package_version_ejabberd_fallback="19.05"
+	export hardcoded_package_version_ejabberd_fallback_extended="19.05-0"
+
 	############################################################################
 	############################################################################
 	############################################################################
@@ -675,7 +682,7 @@ aenigma-install_sslh() {
 
 	fi
 
-	/usr/sbin/service sslh restart
+	service sslh restart
 
 	dna-echo_operation -t
 
@@ -1067,13 +1074,13 @@ aenigma-get_ejabberd_installed_version() {
 
 }
 
-aenigma-get_ejabberd_candidate_version() {
-
-	dna-apt_update
-
-	ejabberd_candidate_version="$(apt-cache show ejabberd | grep Version | head -1 | sed "s|Version: ||" | cut -d ':' -f 2 | cut -f1 -d'-')"
-
-}
+#aenigma-get_ejabberd_candidate_version() {
+#
+#	dna-apt_update
+#
+#	ejabberd_candidate_version="$(apt-cache show ejabberd | grep Version | head -1 | sed "s|Version: ||" | cut -d ':' -f 2 | cut -f1 -d'-')"
+#
+#}
 
 aenigma-install_ejabberd_config() {
 
@@ -1081,34 +1088,30 @@ aenigma-install_ejabberd_config() {
 
 	dna-echo -m "Now creating ejabberd directory and setting custom aenigma config..."
 
-	aenigma-get_ejabberd_candidate_version
-
-	ejabberd_candidate_config_version="$(echo ${ejabberd_candidate_version} | head -c 5)"
-
-	source_ejab_conf_file="${source_dir}/conf/ejabberd/ejabberd-${ejabberd_candidate_config_version}.yml"
+	source_ejab_conf_file="${source_dir}/conf/ejabberd/ejabberd-${hardcoded_package_version_ejabberd}.yml"
 
 	if [ ! -f "${source_ejab_conf_file}" ]
 	then
 
-		### Fallback to ejabberd.yml for v18.12 in case the ejabberd candidate install version isn't among the ones we have config files for
-		source_ejab_conf_file="${source_dir}/conf/ejabberd/ejabberd-18.12.yml"
+		### Fallback to old ejabberd.yml in case the ejabberd candidate install version isn't among the ones we have config files for
+		source_ejab_conf_file="${source_dir}/conf/ejabberd/ejabberd-${hardcoded_package_version_ejabberd_fallback}.yml"
 
 	fi
 
-	mkdir -p "/etc/ejabberd/"
-	cp "${source_ejab_conf_file}" "/etc/ejabberd/ejabberd.yml"
+	mkdir -p "/opt/ejabberd/conf/"
+	cp "${source_ejab_conf_file}" "/opt/ejabberd/conf/ejabberd.yml"
 
 	### Install captcha script
 
 	dna-install_dependencies -p "imagemagick"
 
-	if [ -f "/etc/ejabberd/captcha.sh" ]
+	if [ -f "/opt/ejabberd/captcha.sh" ]
 	then
-		rm "/etc/ejabberd/captcha.sh"
+		rm "/opt/ejabberd/captcha.sh"
 	fi
 
-	curl "https://raw.githubusercontent.com/processone/ejabberd/master/tools/captcha.sh" > "/etc/ejabberd/captcha.sh"
-	chmod +x "/etc/ejabberd/captcha.sh"
+	curl "https://raw.githubusercontent.com/processone/ejabberd/master/tools/captcha.sh" > "/opt/ejabberd/captcha.sh"
+	chmod +x "/opt/ejabberd/captcha.sh"
 	echo
 
 	############################################################################
@@ -1184,8 +1187,8 @@ aenigma-set_permissions() {
 
 	if id "ejabberd" &> /dev/null
 	then
-		chown -R "ejabberd:adm" "/var/log/ejabberd/"
-		chmod -R 755 "/var/log/ejabberd/"
+		chown -R "ejabberd:adm" "/opt/ejabberd/logs/"
+		chmod -R 755 "/opt/ejabberd/logs/"
 	fi
 
 	############################################################################
@@ -1243,13 +1246,49 @@ aenigma-create_ejabberd_locations() {
 	### Create logfile
 
 	dna-echo -m "Now creating logfile..."
-	mkdir -p "/var/log/ejabberd/"
-	touch "/var/log/ejabberd/www_access.log"
+	mkdir -p "/opt/ejabberd/logs/"
+	touch "/opt/ejabberd/logs/www_access.log"
 	dna-echo -m "${g-}Finished creating logfile."
 
 	### Set permissions
 
 	aenigma-set_permissions
+
+}
+
+aenigma-install_ejabberd_deb() {
+
+	############################################################################
+
+	### https://computingforgeeks.com/how-to-install-ejabberd-xmpp-server-on-ubuntu-18-04-ubuntu-16-04/
+
+	############################################################################
+
+	operation_message="installing ejabberd"
+	dna-echo_operation -h
+
+	### Ensure DPKG is available before proceeding.
+
+	dna-check_dpkg_availability
+
+	### Download .deb package
+
+	wget -O "${tmp_project_dir}/ejabberd-${hardcoded_package_version_ejabberd_extended}.deb" "https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/${hardcoded_package_version_ejabberd}/ejabberd_${hardcoded_package_version_ejabberd_extended}_amd64.deb"
+
+	### Install .deb package
+
+	dpkg -i "${tmp_project_dir}/ejabberd-${hardcoded_package_version_ejabberd_extended}.deb" || true
+
+	echo
+
+	### Install service
+
+	updatedb
+
+	cp $(locate ejabberd.service) "/etc/systemd/system"
+
+	systemctl daemon-reload
+	systemctl enable --now ejabberd || true
 
 }
 
@@ -1306,28 +1345,28 @@ aenigma-localize_ejabberd_install() {
 			echo "  - \"${additional_domain}\"" >> "${tmp_project_dir}/additional_domains_ejabberd.txt"
 		done
 
-		sed -i "/  - \"domain.xyz\"/ r ${tmp_project_dir}/additional_domains_ejabberd.txt" "/etc/ejabberd/ejabberd.yml"
+		sed -i "/  - \"domain.xyz\"/ r ${tmp_project_dir}/additional_domains_ejabberd.txt" "/opt/ejabberd/conf/ejabberd.yml"
 
 	fi
 
-	sed -i "s/domain.xyz/${domain}/g" "/etc/ejabberd/ejabberd.yml"
-	sed -i "s/hostname.xyz/${hostname}/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/domain.xyz/${domain}/g" "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "s/hostname.xyz/${hostname}/g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	sed -i "s/public_ipv4-var/${public_ipv4}/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/public_ipv4-var/${public_ipv4}/g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	sed -i "s/admin_mail/${admin_mail}/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/admin_mail/${admin_mail}/g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	sed -i "s/ae.@/ae${node_number}.@/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/ae.@/ae${node_number}.@/g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	sed -i "s/xh.@/xh${node_number}.@/g" "/etc/ejabberd/ejabberd.yml"
-	sed -i "s/xm.@/xm${node_number}.@/g" "/etc/ejabberd/ejabberd.yml"
-	sed -i "s/xp.@/xp${node_number}.@/g" "/etc/ejabberd/ejabberd.yml"
-	sed -i "s/xr.@/xr${node_number}.@/g" "/etc/ejabberd/ejabberd.yml"
-	sed -i "s/xv.@/xv${node_number}.@/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/xh.@/xh${node_number}.@/g" "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "s/xm.@/xm${node_number}.@/g" "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "s/xp.@/xp${node_number}.@/g" "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "s/xr.@/xr${node_number}.@/g" "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "s/xv.@/xv${node_number}.@/g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	sed -i "s/nginx_ejabberd_uploads_external_secret-var/${nginx_ejabberd_uploads_external_secret}/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/nginx_ejabberd_uploads_external_secret-var/${nginx_ejabberd_uploads_external_secret}/g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	sed -i "s/ejabberd-psql-user-password-var/${patroni_ejabberd_password}/g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s/ejabberd-psql-user-password-var/${patroni_ejabberd_password}/g" "/opt/ejabberd/conf/ejabberd.yml"
 
 	sed -i "/INET_DIST_INTERFACE=/c\INET_DIST_INTERFACE=${public_ipv4}" "/etc/default/ejabberd"
 
@@ -2575,7 +2614,7 @@ aenigma-migrate-mnesia-postgresql() {
 		operation_message="applying new_sql_schema directive"
 		dna-echo_operation -h
 
-		sed -i "s|## fqdn: \"server3.example.com\"|new_sql_schema: true|g" "/etc/ejabberd/ejabberd.yml"
+		sed -i "s|## fqdn: \"server3.example.com\"|new_sql_schema: true|g" "/opt/ejabberd/conf/ejabberd.yml"
 
 		service ejabberd restart
 
@@ -3278,9 +3317,9 @@ aenigma-provision_tor() {
 	operation_message="adding .onion hostname to ejabberd hosts"
 	dna-echo_operation -h
 
-	if ! grep -q "${tor_hidden_service_hostname}" "/etc/ejabberd/ejabberd.yml"
+	if ! grep -q "${tor_hidden_service_hostname}" "/opt/ejabberd/conf/ejabberd.yml"
 	then
-		sed -i "/^hosts:$/a \  - \"${tor_hidden_service_hostname}\"" "/etc/ejabberd/ejabberd.yml"
+		sed -i "/^hosts:$/a \  - \"${tor_hidden_service_hostname}\"" "/opt/ejabberd/conf/ejabberd.yml"
 	fi
 
 	dna-echo_operation -t
@@ -3300,10 +3339,10 @@ aenigma-provision_tor() {
 
 	dna-echo_operation -t
 
-	operation_message="restarting ufw"
+	operation_message="restarting SSLH"
 	dna-echo_operation -h
 
-	service ufw restart
+	service sslh restart
 
 	dna-echo_operation -t
 
@@ -3523,11 +3562,11 @@ aenigma-set_loglevel_zero_enabled() {
 
 	### ejabberd
 
-	sed -i "s|^loglevel.*|loglevel: 0|g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s|^loglevel.*|loglevel: 0|g" "/opt/ejabberd/conf/ejabberd.yml"
 
-	if [ ! -z "$(ls /var/log/ejabberd/* 2> /dev/null)" ]
+	if [ ! -z "$(ls /opt/ejabberd/logs/* 2> /dev/null)" ]
 	then
-		rm /var/log/ejabberd/*
+		rm /opt/ejabberd/logs/*
 	fi
 
 	aenigma-restart_ejabberd_if_running
@@ -3572,7 +3611,7 @@ aenigma-set_loglevel_zero_disabled() {
 
 	### ejabberd
 
-	sed -i "s|^loglevel.*|loglevel: 4|g" "/etc/ejabberd/ejabberd.yml"
+	sed -i "s|^loglevel.*|loglevel: 4|g" "/opt/ejabberd/conf/ejabberd.yml"
 
 	aenigma-restart_ejabberd_if_running
 
@@ -3624,9 +3663,9 @@ aenigma-set_mam_off_enabled() {
 
 	### Disable mod_mam in ejabberd.yml.
 
-	sed -i '/^\  mod_mam/,/^\    cache_life_time/{//!d}' "/etc/ejabberd/ejabberd.yml"
-	sed -i "s|^\  mod_mam:|#  mod_mam: {}|g" "/etc/ejabberd/ejabberd.yml"
-	sed -i "/^\    cache_life_time/d" "/etc/ejabberd/ejabberd.yml"
+	sed -i '/^\  mod_mam/,/^\    cache_life_time/{//!d}' "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "s|^\  mod_mam:|#  mod_mam: {}|g" "/opt/ejabberd/conf/ejabberd.yml"
+	sed -i "/^\    cache_life_time/d" "/opt/ejabberd/conf/ejabberd.yml"
 
 	############################################################################
 
@@ -3689,7 +3728,7 @@ backup_locally_loop() {
 	mkdir -p "${tmp_backup_dir}"/data/
 	/usr/sbin/ejabberdctl backup ejabberd-mnesia-backup
 	mv /var/lib/ejabberd/ejabberd-mnesia-backup "${tmp_backup_dir}"/data/ejabberd-mnesia-backup
-	cp -r /etc/ejabberd/ "${tmp_backup_dir}"/data/etc-ejabberd/
+	cp -r /opt/ejabberd/ "${tmp_backup_dir}"/data/etc-ejabberd/
 	cp -r /var/lib/ejabberd/ "${tmp_backup_dir}"/data/var-lib-ejabberd/
 
 	if [ "${cluster_enabled}" = "y" ]
@@ -3760,7 +3799,7 @@ restore_loop() {
 	echo "${b-}3] Now syncing ejabberd directories...${x-}"
 	echo
 
-	rsync -aAXx --delete $restore_file_path/data/etc-ejabberd/ /etc/ejabberd/
+	rsync -aAXx --delete $restore_file_path/data/etc-ejabberd/ /opt/ejabberd/
 	rsync -aAXx --delete $restore_file_path/data/var-lib-ejabberd/ /var/lib/ejabberd/
 
 	aenigma-set_permissions
@@ -3931,7 +3970,7 @@ synthia-perform_installation() {
 
 	if dpkg -s ejabberd &> /dev/null
 	then
-		if ! grep -q "default_db: sql" "/etc/ejabberd/ejabberd.yml"
+		if ! grep -q "default_db: sql" "/opt/ejabberd/conf/ejabberd.yml"
 		then
 			export psql_migration_required="true"
 		fi
@@ -4803,17 +4842,16 @@ synthia-perform_installation() {
 
 		### ejabberd is currently installed. Check if an ejabberd upgrade is going to be performed.
 
-		aenigma-get_ejabberd_candidate_version
-
-		if [ ! "${ejabberd_candidate_version}" = "${ejabberd_installed_version}" ]
+		if [ ! "${hardcoded_package_version_ejabberd}" = "${ejabberd_installed_version}" ]
 		then
 
-			dna-echo -s "A new version of ejabberd is available from the APT repository. Upgrading it now..."
+			dna-echo -s "A new version of ejabberd is available. Upgrading it now..."
 
-			### Upgrade ejabberd by non-interactively installing the new config files
-			### [which we'll the re-replace later in the installation anyway].
+			### Upgrade ejabberd by non-interactively installing the new config
+			### files [which we'll the re-replace later in the installation
+			### anyway].
 
-			export DEBIAN_FRONTEND=noninteractive ; apt-get install -y -o Dpkg::Options::="--force-confnew" --force-yes --only-upgrade ejabberd || true
+			dpkg -i "${tmp_project_dir}/ejabberd-${ejabberd_candidate_version}" || true
 
 		fi
 
@@ -4946,8 +4984,8 @@ synthia-perform_installation() {
 
 	declare -A service_checker_array=(
 			[APT]="apt-get -y upgrade"
-			[NGINX]="/usr/sbin/service nginx restart"
-			[SSLH]="/usr/sbin/service sslh restart"
+			[NGINX]="service nginx restart"
+			[SSLH]="service sslh restart"
 		)
 
 	add_service_check_bottom_spacing() {
@@ -5053,7 +5091,7 @@ synthia-perform_installation() {
 			dna-echo -s "The ejabberd cluster was successfully joined!"
 		else
 			dna-echo -e "The ejabberd cluster join operation failed."
-			dna-echo -m "Inspect the | ${y-}/var/log/ejabberd/error.log${n-} | logfile for more information."
+			dna-echo -m "Inspect the | ${y-}/opt/ejabberd/logs/error.log${n-} | logfile for more information."
 			dna-exit
 		fi
 
@@ -5175,11 +5213,11 @@ synthia-perform_installation() {
 	if [ "${dh_param_status}" = "ok" ]
 	then
 
-		if grep -q "### dhfile" "/etc/ejabberd/ejabberd.yml"
+		if grep -q "### dhfile" "/opt/ejabberd/conf/ejabberd.yml"
 		then
 
-			sed -i "s|### dhfile: 'DHFILE'|dhfile: 'DHFILE'|g" "/etc/ejabberd/ejabberd.yml"
-			sed -i "s|### s2s_dhfile: 'DHFILE'|s2s_dhfile: 'DHFILE'|g" "/etc/ejabberd/ejabberd.yml"
+			sed -i "s|### dhfile: 'DHFILE'|dhfile: 'DHFILE'|g" "/opt/ejabberd/conf/ejabberd.yml"
+			sed -i "s|### s2s_dhfile: 'DHFILE'|s2s_dhfile: 'DHFILE'|g" "/opt/ejabberd/conf/ejabberd.yml"
 
 			dna-echo -m "Now restarting ejabberd..."
 
