added get_nodes_online

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -863,6 +863,53 @@ aenigma-refresh_nodes_db_online() {
 
 }
 
+aenigma-get_nodes_online() {
+
+	############################################################################
+
+	### Generate a list of online nodes by opening SSH sessions to other nodes.
+	### If any nodes are offline, remove them from nodes_db_online.
+
+	aenigma-refresh_nodes_db_online
+
+	array_iter=1
+	IFS=$'\n'
+	set -f
+
+	touch "${tmp_project_dir}/online_test_token"
+
+	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")							### Do NOT escape this variable
+	do
+		node_number="$(echo ${array_iter} | xargs printf %02d)"
+		### Ensure we don't try connecting to ourselves [therefore ignore the first line of nodes_db_ipv4].
+		if [ ! "${node_ipv4}" = "${public_ipv4}" ]
+		then
+			if ! /usr/bin/scp -P42022 -o "ConnectTimeout=8" -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i "/root/.ssh/aenigma_cluster" -r "${tmp_project_dir}/online_test_token" "root@${node_ipv4}:/tmp/aenigma/"
+			then
+				echo
+				dna-echo -e "Existing node number | ${n-}${node_number}${r-} | is not responding at IPv4 address | ${n-}${node_ipv4}${r-} |."
+				dna-echo -m "It is NOT reccommended to continue the installation as the node in question will not be informed of the new node we're setting up right now."
+				dna-echo -m "However, you can continue running the installation now and re-run the installation script at at a later time."
+	            dna-ask_for_boolean -d "y" -q "Continue anyway?"
+	            if [ "${boolean_output}" = "y" ]
+	            then
+					dna-echo -n -m "Ok, continuing..."
+					### Remove node from nodes_db_online
+					sed -i "/^${node_ipv4}$/d" "${nodes_db_online_path}"
+				else
+					dna-echo -m "Ok, aborting..."
+					dna-exit
+				fi
+			fi
+		fi
+		array_iter=$((array_iter + 1))
+	done
+	unset node_ipv4
+	IFS=$' \t\n'
+	set +f
+
+}
+
 aenigma-check_ip_info_current() {
 
 	if [ ! -f "${nodes_db_ipv4_path}" ] || [ ! -f "${nodes_db_ipv6_path}" ]
