Handle offline existing secondary nodes during a new clusterization

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -45,6 +45,7 @@ define_vars() {
 	nodes_db_ipv4_path="${conf_cluster_nodes_dir}/nodes_db_ipv4"
 	nodes_db_ipv6_path="${conf_cluster_nodes_dir}/nodes_db_ipv6"
 	nodes_db_numbered_path="${conf_cluster_nodes_dir}/nodes_db_numbered"
+	nodes_db_online_path="${temp_dir}/nodes_db_online"
 
 	############################################################################
 	############################################################################
@@ -600,19 +601,62 @@ aenigma-update_routing_info() {
 
 }
 
+aenigma-create_nodes_db_online() {
+
+	### This function will always get invoked at the beginning push_routing_info() in the later event that an existing node cannot be reached at the time of running a new clusterization.
+	### It will create a copy of nodes_db_ipv4 and nodes that appear to be offline will be removed fromit, for use by subsequent functions, until the end of the clusterize script.
+
+	mkdir -p "${temp_dir}"
+
+	if [ -f "${nodes_db_online_path}" ]
+	then
+		rm "${nodes_db_online_path}"
+		touch "${nodes_db_online_path}"
+	fi
+
+	cp "${nodes_db_ipv4_path}" "${nodes_db_online_path}"
+
+}
+
 aenigma-push_routing_info() {
 
 	############################################################################
 
-	### Push nodes_db files to secondary node for /etc/hosts and ufw rules configuration
+	### Push nodes_db files to all secondary nodes for /etc/hosts and ufw rules configuration
+	### At the same time, check to see if any existing secondary nodes are offline, and, if so, remove them from nodes_db_online
+
+	aenigma-create_nodes_db_online
+
+	array_iter=1
+	IFS=$'\n'
+	set -f
 
 	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")
 	do
+		node_number="$(echo ${array_iter} | xargs printf %02d)"
 		### Ensure we don't try connecting to ourselves [therefore ignoring the first line of nodes_db_ipv4].
 		if [ ! "${node_ipv4}" = "${this_ipv4}" ]
 		then
-			/usr/bin/scp -P42022 -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i /root/.ssh/aenigma_cluster -r "${conf_cluster_nodes_dir}" "root@${node_ipv4}:${conf_cluster_dir}"
+			if ! /usr/bin/scp -P42022 -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i /root/.ssh/aenigma_cluster -r "${conf_cluster_nodes_dir}" "root@${node_ipv4}:${conf_cluster_dir}"
+			then
+				dna-echo -e "Existing node number | ${n-}${node_number}${r-} | is not responding at IPv4 address | ${n-}${node_ipv4}${r-} |."
+				dna-echo -m "It is NOT reccommended to continue the configuration as the node in question will not be informed of the new node we're setting up right now."
+				dna-echo -m "However, you can continue runing the installation now and run the | ${o-}push_routing_info${n-} | script at at a later time by executing:"
+				dna-echo -m " | ${y-}bash ${tools_dir}/${short_name}-push_routing_info${n-} | "
+				ask_for_boolean_question="Continue with installation anyway?"
+	            dna-ask_for_boolean_def_yes
+	            if [ "$ask_for_boolean_output" = "y" ]
+	            then
+					dna-echo -m "Ok, continuing..."
+					### Remove node from nodes_db_online
+					sed -i "/^${node_ipv4}$/d" "${nodes_db_online_path}"
+				else
+					dna-echo -m "Ok, aborting installation..."
+					dna-exit
+				fi
+			fi
 		fi
+		array_iter=$((array_iter + 1))
 	done
 	unset node_ipv4
 
@@ -630,13 +674,13 @@ aenigma-update_routing_info
 
 	############################################################################
 
-	for node_ipv4 in $(cat < "${nodes_db_ipv4_path}")
+	for online_node_ipv4 in $(cat < "${nodes_db_online_path}")
 	do
 		### Ensure we don't try connecting to ourselves [therefore ignoring the first line of nodes_db_ipv4].
-		if [ ! "${node_ipv4}" = "${this_ipv4}" ]
+		if [ ! "${online_node_ipv4}" = "${this_ipv4}" ]
 		then
 			### SSH into the secondary node, declare the aenigma-exec function, and run it inside of the subshell.
-	        ssh -tt -p42022 -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i "/root/.ssh/aenigma_cluster" "root@${node_ipv4}" "$(declare -f aenigma-exec); export -f aenigma-exec; exec bash -li" <<END
+	        ssh -tt -p42022 -o "LogLevel=ERROR" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i "/root/.ssh/aenigma_cluster" "root@${online_node_ipv4}" "$(declare -f aenigma-exec); export -f aenigma-exec; exec bash -li" <<END
 set -eu
 aenigma-exec
 exit
@@ -644,7 +688,7 @@ END
 		fi
 		echo
 	done
-	unset node_ipv4
+	unset online_node_ipv4
 
 	############################################################################
 
