listen for custom project arguments in /setup, add -un to skip apt_upgrade during install to fix https://github.com/openspace42/aenigma/issues/79

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -70,6 +70,7 @@ synthia-define_formatting
 synthia-check_root
 
 ################################################################################
+################################################################################
 
 ### Head setup
 
@@ -143,9 +144,42 @@ synthia-source_dna
 synthia-define_vars
 
 ################################################################################
+################################################################################
+
+### Evaluate project_specific command arguments
+
+while getopts ":u:" arguments
+do
+    case $arguments in
+        u)  export apt_upgrade="${OPTARG}"
+            ;;
+        ;;
+        \?)	echo "${r-}${b-}Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
+	        echo
+			echo "${b-}Exiting...${x-}"
+			echo
+	        exit 1
+	        ;;
+    esac
+done
+OPTIND=1
+
+if [ -n "${apt_upgrade-}" ]
+then
+	case "${apt_upgrade}" in
+		n)	apt_upgrade="none"
+			;;
+		*)	dna-echo -e "Invalid content for describe argument in function | ${n-}${FUNCNAME[0]}${r-} |."
+			dna-exit
+			;;
+	esac
+fi
+
+################################################################################
 
 ### Actually run the installer
 
 dna-run_install
 
+################################################################################
 ################################################################################
